x ="*SC5@dHb#H:5[w8*<@>kB;F&]>:]BvRr1nai"
print(ord('*'))
print(ord('S'))
print(ord('C'))
print(ord('5'))
print(ord('@'))
print(ord('d'))
print(ord('H'))
print(ord('b'))
print(ord('#'))
print(ord('H'))
print(ord(':'))
print(ord('5'))
print(ord('['))
print(ord('w'))
print(ord('8'))
print(ord('*'))
print(ord('<'))
print(ord('@'))
print(ord('>'))
print(ord('k'))
print(ord('B'))
print(ord(';'))
print(ord('F'))
print(ord('&'))
print(ord(']'))
print(ord('>'))
print(ord(':'))
print(ord(']'))
print(ord('B'))
print(ord('v'))
print(ord('R'))
print(ord('r'))
print(ord('1'))
print(ord('n'))
print(ord('a'))
print(ord('i'))




